// user
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const UPDATE_STATUS_NOTIFICATIONS_READ =
  "UPDATE_STATUS_NOTIFICATIONS_READ";

// UI
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// data
export const LOADING_DATA = "LOADING_DATA";
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_PROJECT = "SET_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const JOIN_PROJECT = "LIKE_PROJECT";
export const LEAVE_PROJECT = "UNLIKE_PROJECT";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const LIKE_PROJECT = "LIKE_PROJECT";
export const UNLIKE_PROJECT = "UNLIKE_PROJECT";
export const FIRE_PROJECT = "FIRE_PROJECT";
export const UNFIRE_PROJECT = "UNFIRE_PROJECT";
export const LAUGH_PROJECT = "LAUGH_PROJECT";
export const UNLAUGH_PROJECT = "UNLAUGH_PROJECT";
export const ROCKET_PROJECT = "ROCKET_PROJECT";
export const UNROCKET_PROJECT = "UNROCKET_PROJECT";
export const CONFUSED_PROJECT = "CONFUSED_PROJECT";
export const UNCONFUSED_PROJECT = "UNCONFUSED_PROJECT";
